// src/Angular/ClientApp/app/components/data-tables/grid.component.ts
import { Component, OnInit, Output, Input, OnChanges, EventEmitter } from '@angular/core';
import { Models } from './../../root';

@Component({
    selector: 'grid',
    templateUrl: './grid.component.html',
    styleUrls: ['./grid.component.css']
})
export class GridComponent implements OnChanges {

    @Input() metadata;
    @Input() request: Models.IGridState;
    @Input() api;
    @Input() links: ILink[];
    @Output() change = new EventEmitter();
    data: any[];
    columns: Models.IUIMetadata[];
    constructor() { }

    ngOnChanges() {
        console.log('metadata=' + this.metadata);
        console.log('request=' + this.request);
        console.log('api=' + this.api);

        if (this.metadata && this.request && this.api)
            this.setup();
    }
    setup() {
        console.log('setup');
        if (!this.columns) {
            this.columns = [];
            for (var key in this.metadata) {
                if (this.metadata.hasOwnProperty(key)
                    && (!this.metadata[key].isHidden ||
                        this.metadata[key].isHidden == false)
                ) {
                    this.columns.push(this.metadata[key]);
                }
            }
        }
        this.refresh();
    }
    refresh() {
        this.change.emit({});
        if (!this.api || typeof this.api.get != "function")
            console.error('api class is not set or does not have a get function');
        var response = this.api.get(this.request);
        if (response.isOk) {
            this.data = response.data;
            this.request = response.gridState;
        }
    }
    format(value: string, format: string) {
        if (value == null)
            return '';
        try {
            switch (format) {
                case "Text":
                    return value;
                case "Date":
                    var date = new Date(value);
                    return date.toLocaleDateString("en-US");
                case "Time":
                    var date = new Date(value);
                    return date.toTimeString();
                case "DateTime":
                    var date = new Date(value);
                    return date.toLocaleString();
                case "Currency":
                    var number = parseFloat(value);
                    return "$" + number.toFixed(3);
                case "Decimal":
                    var number = parseFloat(value);
                    return number.toFixed(3);
                case "PhoneNumber":
                    if (value.length == 10) {
                        var first = value.substr(0, 3);
                        var second = value.substr(3, 3);
                        var third = value.substr(6, 4);
                        return `(${first}) #{second}-${third}`;
                    }
                    else {
                        return value;
                    }
            }
        }
        catch (e) {
            console.log(e);
            return value;
        }
    }
}
export interface ILink {
    text: string;
    action: (any) => void;
    icon: string;
}




<div class="mdc-card">
    
    <span  class="mdi mdi-arrow-down"></span>
    <table class="data-table mdc-card__primary">
        <thead class="mdc-typography--body2">
        <tr>
            <th *ngIf="links && links.length > 0"></th>
            <th *ngFor="let column of columns" class="">
                <span *ngIf="column.doNotSort && column.doNotSort == true">{{column.DisplayName}}</span>
                <sorter *ngIf="!column.doNotSort || column.doNotSort == false"
                        [(member)]="column.propertyName"
                        [(text)]="column.displayName"
                        [(request)]="request"
                        (change)="refresh()"></sorter>
            </th>
        </tr>
        </thead>
        <tbody class="mdc-typography--body1">
        <tr *ngFor="let row of rows">
            <td class="button-column" *ngIf="links && links.length > 0">
                <button *ngFor="let link of links" type="button"
                        (click)="link.action != null && link.action(row)"
                        class="btn btn-sm btn-primary">
                    <i [ngClass]="'fa fa-fw fa-'+link.icon"></i>{{link.text}}
                </button>
            </td>
            <td *ngFor="let column of columns">
                {{format(row[column.ColumnName], column.Format)}}
            </td>
        </tr>
        </tbody>
    </table>
    <section className="mdc-card__supporting-text"></section>
    <section className="mdc-card__actions">
        Pager
    </section>
</div>

// src/React/ClientApp/components/data-table/grid/grid.tsx
﻿import * as React from 'react';
import { observable, Models, Services } from './../../../root';
import { Sorter } from './../sorter';
import { Pager } from './../pager/pager';
import { GridButton } from './grid-button';
import { PushButton } from './../../buttons/push-button';

export class GridProps {
    request: Models.IGridState = { sortMember: '', sortDirection: '' };
    refresh: (request: Models.IGridState) => void;
    buttons?: GridButton[];
    metadata;
    data: any[];
}
export class Grid extends React.Component<GridProps, any>
{
    columns: Models.UIMetadata[] = [];
    constructor(props)
    {
        super(props);
        this.render.bind(this);
    }
    executeAction = (action, row) => {
        if (action && typeof action == "function")
            action(row);
    }

    render() {
        debugger;
        this.columns = Services.FormsService.getProperties(this.props.metadata);
        let headings = this.columnHeadings();
        return <div className="mdc-card">
            <table className="data-table mdc-card__primary">
                <thead className="mdc-typography--body2">
                    <tr>
                        {this.props.buttons && this.props.buttons.length > 0 && <th ></th>}
                        {headings}
                    </tr >
                </thead >
                <tbody className="mdc-typography--body1">
                    {this.props.data.map(this.rows)}
                </tbody>
            </table>
            <section className="mdc-card__supporting-text"></section>
            <section className="mdc-card__actions pager-container">
                <Pager request={this.props.request} refresh={this.props.refresh}></Pager>
            </section>
        </div>;
    }

    columnHeadings () {
        return this.columns.map((column) => {
            var dontSort = column.doNotSort != null && column.doNotSort;
            return <th key={column.jsName}>
                {dontSort && <span >{column.displayName}</span>}
                {!dontSort &&
                    <Sorter member={column.propertyName}
                        text={column.displayName}
                        request={this.props.request}
                        refresh={this.props.refresh}></Sorter >}
            </th>;
        });
    }

    rows(row) {
        debugger;
        const buttons = this.props.buttons;
        const hasButtons = buttons && buttons.length > 0;
        const rowButtons = buttons.map((button) => {
            return <PushButton theme="primary"
                text={button.text} icon={button.icon} click={this.executeAction(button.action, row)}
            ></PushButton>;
        });
        debugger;
        const cells = this.columns.map((column) => {
            debugger;
            return <td>{Services.FormatService.format(row[column.jsName], column)}</td>;
        });
        return <tr>
            {hasButtons && <td className="button-column" >{rowButtons}</td >}
            {cells}
        </tr>;
    }

}
