// src/React/ClientApp/components/data-table/sorter.tsx
﻿import * as React from 'react';
import { observable, Models } from './../../root';

export class SorterProps {
    member: string = '';
    text: string = '';
    request: Models.IGridState = { sortMember: '', sortDirection: '' };
    refresh: (request: Models.IGridState) => void;
}
export class Sorter extends React.Component<SorterProps, any>
{
    currentSortKey: string;
    member: string = '';
    text: string = '';
    gridState: Models.IGridState = { sortMember: '', sortDirection: '' };

    constructor(props: SorterProps) {        
        super(props);
        this.gridState = props.request;
        this.text = props.text;
        this.member = props.member;
    }
    
    isCurrentSortAsc= () => {
        return  this.gridState &&
                this.gridState.sortMember == this.member && 
            this.gridState.sortDirection == "ASC";
    }

    isCurrentSortDesc = () => {
        return this.gridState &&
            this.gridState.sortMember == this.member &&
            this.gridState.sortDirection == "DESC";
    }   

    sort = (member) => {
        if (this.gridState.sortMember != null && this.gridState.sortDirection != null
            && member.toUpperCase() === this.gridState.sortMember.toUpperCase())
            this.gridState.sortDirection = this.gridState.sortDirection === "ASC" ? "DESC" : "ASC";
        else
            this.gridState.sortDirection = "ASC";
        this.gridState.sortMember = member;
        this.props.refresh(this.gridState);
    }

    render() {       
        var showUp = this.isCurrentSortAsc();
        var showDown = this.isCurrentSortDesc();
        var showFaded = !showUp && !showDown;

        var upArrow = <i className="mdi mdi-arrow-up"></i>;
        var downArrow = <i className="mdi mdi-arrow-down"></i>;
        var fadedArrow = <span className="available-sort-indicator">
            <i className="mdi mdi-arrow-up"></i>
        </span>;
        return <span>
            <span className="sort-indicator">                
                {showUp && upArrow}
                {showDown && downArrow}
                {showFaded && fadedArrow}
             </span>
            <span className="sorter" onClick={() => this.sort(this.member)}>
                {this.text}
            </span>
        </span>
    }
}

// src/Angular/ClientApp/app/components/data-tables/sorter.component.ts
import { Component, OnInit, Output, Input, EventEmitter, DoCheck } from '@angular/core';
import { Models } from './../../root';

@Component({
  selector: 'sorter',
  templateUrl: './sorter.component.html',
  styleUrls: ['./sorter.component.css']
})
export class SorterComponent implements DoCheck {
    @Input() public gridState: Models.IGridState;
    @Input() member: string = '';
    @Input() text: string = '';
    @Output() change = new EventEmitter();
    constructor() {
        this.currentSortKey = '';
    }

    ngDoCheck() {
        if (this.gridState == null || this.gridState.totalRecords == undefined ||
            this.gridState.totalRecords == 0) {
            return;
        }
        else {
            this.setup();
        }
    }


  setup = () => {
      this.currentSort = this.gridState.sortDirection + this.gridState.sortMember;
      this.isCurrentSortAsc = this.checkIfCurrentSortAsc(this.member);
      this.isCurrentSortDesc = this.checkIfCurrentSortDesc(this.member);
  }

  checkIfCurrentSortAsc = (member) => {      
      if (this.gridState === null || this.gridState.sortMember == null || this.gridState.sortDirection == null)
          return false;
      return this.gridState.sortMember.toUpperCase() === member.toUpperCase()
          && this.gridState.sortDirection.toUpperCase() === "ASC";
  }

  checkIfCurrentSortDesc = (member) => {      
      if (this.gridState === null || this.gridState.sortMember == null || this.gridState.sortDirection == null)
          return false;
      return this.gridState.sortMember.toUpperCase() === member.toUpperCase()
          && this.gridState.sortDirection.toUpperCase() === "DESC";
  }

  sort = (member) => {
      this.setup();
      if (member.toUpperCase() === this.gridState.sortMember.toUpperCase())
          this.gridState.sortDirection = this.gridState.sortDirection === "ASC" ? "DESC" : "ASC";
      else
          this.gridState.sortDirection = "ASC";
      this.gridState.sortMember = member;
      let e = new CustomEvent('change', {
          bubbles: true
      });
      this.change.emit({});
  }

  currentSort: string;
  currentSortKey: string;
  isCurrentSortAsc: boolean;
  isCurrentSortDesc: boolean;
}

<span>
    <span className="sort-indicator">
        <i *ngIf="this.isCurrentSortAsc" class="mdi mdi-arrow-up"></i>
        <i *ngIf="this.isCurrentSortDesc" class="mdi mdi-arrow-down"></i>;
        <span *ngIf="!this.isCurrentSortDesc && !isCurrentSortAsc"
              className="available-sort-indicator">
            <i className="mdi mdi-arrow-up"></i>
        </span>
    </span>
    <span className="sorter" onClick=(this.sort(this.member)>
        {{this.text}}
    </span>
</span>
