// src/Angular/ClientApp/app/components/pager.component.ts
import { Component, OnInit, Output, Input, EventEmitter, DoCheck } from '@angular/core';
import { Models } from './../root';
@Component({
    selector: 'pager',
    templateUrl: './pager.component.html',
    styleUrls: ['./pager.component.css']
})

export class PagerComponent implements DoCheck {
    @Input() public gridState: Models.IGridState;

    @Output() change = new EventEmitter();
    pageBlock: any[];
    isLastBlock: boolean = false;
    isFirstBlock: boolean = false;
    isFirstPage: boolean = false;
    isLastPage: boolean = false;
    hasRecords: boolean = false;
    totalPages: number = 0;
    blockSize: number = 10;
    nextBlockPage: number;
    prevBlockPage: number;
    recordsVerbiage: string;


    constructor() {

        this.pageBlock = [];
        this.isLastBlock = false;
        this.isFirstBlock = false;
        this.isFirstPage = false;
        this.isLastPage = false;
        this.hasRecords = false;
        this.totalPages = 0;
        this.blockSize = 10;
        this.hasRecords = false;
    }

    ngDoCheck() {
        if (this.gridState.totalRecords == 0) {
            this.gridState.pageNumber = 1;
            this.hasRecords = false;
            return;
        }
        else {
            this.setup();
        }
    }

    public resetPagingIfNeeded = () => {
        if (this.gridState != null && this.gridState.resetPaging)
            this.gridState.pageNumber = 1;
    };
    
    public setup = () => {
        if (this.gridState.totalRecords == undefined) {
            this.hasRecords = false;
            return;
        }
        this.hasRecords = this.gridState.totalRecords !== 0;

        this.totalPages = Math.ceil(this.gridState.totalRecords / this.gridState.pageSize);
        var blocks = [];
        var blockNumber = Math.ceil(this.gridState.pageNumber / this.blockSize) - 1;
        var blockStart = blockNumber * this.blockSize;
        var min = blockStart + 1;
        var max = blockStart + this.blockSize;

        for (let i = 1; i < this.blockSize + 1; i++) {
            if (blockStart + i < this.totalPages + 1)
                blocks.push({ page: blockStart + i, isActive: blockStart + i === this.gridState.pageNumber });
        }
        this.pageBlock = blocks;

        var pageNumber = this.gridState.pageNumber;
        this.prevBlockPage = min - 1;
        this.nextBlockPage = max + 1;

        this.isLastBlock = this.pageBlock.length > 0 && max >= this.totalPages;
        this.isFirstBlock = min === 1;
        this.isFirstPage = pageNumber === 1;
        this.isLastPage = this.totalPages === pageNumber;
        var startRow = ((pageNumber - 1) * this.gridState.pageSize) + 1;
        var endRow = startRow + this.gridState.pageSize - 1;
        if (this.isLastPage)
            endRow = this.gridState.totalRecords;

        this.recordsVerbiage = 'Showing ' + startRow + ' to ' + endRow + ' of ' + this.gridState.totalRecords;
    }
    public changePageSize()
    {
        this.gridState.pageNumber = 1;
        this.update();
    }
    public update = () => {
        this.page(<number>this.gridState.pageNumber);
    }
    public page = (number: number) => {
        this.gridState.pageNumber = number;
        this.change.emit({});
    };
    public firstPage = () => {
        return this.page(1);
    };
    public prevBlock = () => {
        return this.page(this.prevBlockPage);
    };
    public prevPage = () => {
        return this.page(<number>this.gridState.pageNumber - 1);
    };
    public nextPage = () => {
        return this.page(<number>this.gridState.pageNumber + 1);
    };
    public nextBlock = () => {
        return this.page(this.nextBlockPage);
    };
    public lastPage = () => {
        return this.page(this.totalPages);
    };


}




    <div class="row pager-container">
        <div class="pagination"
             *ngIf="hasRecords"
             style="margin: 0px 0px 0px 0px;">
            <div style="float: left; margin-right: 20px; white-space: nowrap;">
                <label style="float: left; margin-right: 4px; margin-top: 6px;">Page Size</label>
                <select [(ngModel)]="pagedResult.PaginationInfo.PageSize" (change)="changePageSize()"

                        class="form-control" style="width: 80px; float: left;">
                    <option>10</option>
                    <option>25</option>
                    <option>50</option> 
                    <option>100</option>
                </select>
            </div>
            <div style="float: left; vertical-align: top;">
                <ul class="pagination" style="margin: 0px 0px 0px 0px;">
                    <li [ngClass]="{'disabled':isFirstPage}">
                        <a [class.disabled]="isFirstPage"
                           (click)="!isFirstPage && firstPage()">&laquo;</a>
                    </li>
                    <li [ngClass]="{'disabled':isFirstPage}">
                        <a [class.disabled]="isFirstBlock"
                           (click)="!isFirstBlock && prevBlock()">...</a>
                    </li>
                    <li [ngClass]="{'disabled':isFirstPage}">
                        <a [class.disabled]="isFirstPage"
                           (click)="!isFirstPage && prevPage()">&lt;</a>
                    </li>
                    <li *ngFor="let block of pageBlock" [ngClass]="{'active':block.isActive}">
                        <a (click)="page(block.page)">{{block.page}}</a>
                    </li>
                    <li [ngClass]="{'disabled':isLastPage}">
                        <a [class.disabled]="isLastPage"
                           (click)="!isLastPage && nextPage()">&gt;</a>
                    </li>
                    <li [ngClass]="{'disabled':isLastBlock}">
                        <a [class.disabled]="isLastBlock"
                           (click)="!isLastBlock && nextBlock()">...</a>
                    </li>
                    <li [ngClass]="{'disabled':isLastPage}">
                        <a [class.disabled]="isLastPage"
                           (click)="!isLastPage && lastPage()">&raquo;</a>
                    </li>
                </ul>
                <div>
                    {{recordsVerbiage}}
                </div>
            </div>

        </div>
        <div id="norecords" *ngIf="!hasRecords">
            <h3>No records found</h3>
        </div>
    </div>

// src/React/ClientApp/components/data-table/pager/pager.tsx
﻿import * as React from 'react';
import { Models, observer, observable, IObservableValue, IObservableArray } from './../../../root';
import { PageBlock } from './page-block';
import { PagerButton } from './pager-button';
export class PagerProps {
    request: Models.IGridState;
    refresh: (request: Models.IGridState) => void;
}

export class Pager extends React.Component<PagerProps, any>
{
    pageBlock: IObservableArray<PageBlock> = observable([]);
    isLastBlock: boolean = false;
    isFirstBlock: boolean = false;
    isFirstPage: boolean = false;
    isLastPage: boolean = false;
    hasRecords: IObservableValue<boolean> = observable(false);
    totalPages: number = 0;
    blockSize: number = 10;
    nextBlockPage: number;
    prevBlockPage: number;
    recordsVerbiage: string;
    gridState: Models.IGridState;

    constructor(props: PagerProps) {
        super(props);
        this.gridState = observable(props.request);
    }
    public resetPagingIfNeeded = () => {
        if (this.gridState != null && this.gridState.resetPaging)
            this.gridState.pageNumber = 1;
    };
    public setup = () => {
        if (this.gridState.totalRecords == undefined) {
            this.hasRecords.set(false);
            return;
        }
        this.hasRecords.set(this.gridState.totalRecords !== 0);

        this.totalPages = Math.ceil(this.gridState.totalRecords / this.gridState.pageSize);
        var blocks = [];
        var blockNumber = Math.ceil(this.gridState.pageNumber / this.blockSize) - 1;
        var blockStart = blockNumber * this.blockSize;
        var min = blockStart + 1;
        var max = blockStart + this.blockSize;

        for (let i = 1; i < this.blockSize + 1; i++) {
            if (blockStart + i < this.totalPages + 1)
                blocks.push({ page: blockStart + i, isActive: blockStart + i === this.gridState.pageNumber });
        }
        this.pageBlock.replace(blocks);

        var pageNumber = this.gridState.pageNumber;
        this.prevBlockPage = min - 1;
        this.nextBlockPage = max + 1;

        this.isLastBlock = this.pageBlock.length > 0 && max >= this.totalPages;
        this.isFirstBlock = min === 1;
        this.isFirstPage = pageNumber === 1;
        this.isLastPage = this.totalPages === pageNumber;
        var startRow = ((pageNumber - 1) * this.gridState.pageSize) + 1;
        var endRow = startRow + this.gridState.pageSize - 1;
        if (this.isLastPage)
            endRow = this.gridState.totalRecords;

        this.recordsVerbiage = 'Showing ' + startRow + ' to ' + endRow + ' of ' + this.gridState.totalRecords;
    }
    public update = () => {
        this.page(this.gridState.pageNumber);
    }
    public page = (number) => {

        this.gridState.pageNumber = number;
        this.props.refresh(this.gridState);
    };
    public firstPage = () => {
        return this.page(1);
    };
    public prevBlock = () => {
        return this.page(this.prevBlockPage);
    };
    public prevPage = () => {
        return this.page(this.gridState.pageNumber - 1);
    };
    public nextPage = () => {
        return this.page(this.gridState.pageNumber + 1);
    };
    public nextBlock = () => {
        return this.page(this.nextBlockPage);
    };
    public lastPage = () => {
        return this.page(this.totalPages);
    };

    render() {
        this.setup();
        var noRecords = <div id="norecords" ><h3 className="mdc-typography--body2">No records found</h3></div>;
        var pager = this.pager();
        return <div>
            {!this.hasRecords && noRecords}
            {this.hasRecords && pager}
        </div>;
    }

    pageSizeSelector = () => {
        var wrapperStyle =
            {
                float: 'left',
                marginRight: '20px',
                whiteSpace: 'nowrap'

            };
        var labelStyle = {
            float: 'left',
            marginRight: '20px',
            whiteSpace: 'nowrap'
        }
        return <div className="mdc-form-field">
            <label>Page Size</label>
            <select
                value={this.gridState.pageSize}
                onChange={this.props.refresh}
            >
                <option>10</option>
                <option>25</option>
                <option>50</option>
                <option>100</option>
            </select>
        </div >;
    }
    pager = () => {
        console.log('pager method');
        var buttons = this.pageBlock.map(
            (block) => {
                return <PagerButton text={block.page.toString()} isDisabled={this.isFirstPage} method={this.page(block.page)} isActive={block.isActive} />
            });
        return <div>
            <div className="pagination">
                <PagerButton text="&laquo;" isDisabled={this.isFirstBlock} method={this.firstPage} isActive={false} />
                <PagerButton text="..." isDisabled={this.isFirstPage} method={this.prevPage} isActive={false} />
                <PagerButton text="&lt;" isDisabled={this.isFirstBlock} method={this.prevBlock} isActive={false} />
                {buttons}
                <PagerButton text="&gt;" isDisabled={this.isLastPage} method={this.nextPage} isActive={false} />
                <PagerButton text="..." isDisabled={this.isLastBlock} method={this.nextBlock} isActive={false} />
                <PagerButton text="&raquo;" isDisabled={this.isLastPage} method={this.lastPage} isActive={false} />

                <div>
                    <span className="mdc-typography--body1">{this.recordsVerbiage}</span>
                </div>
            </div >
        </div>
    }
}
